import type { Metadata } from "next";
import "../../app/globals.css";
import Private from "./nice/_components/private";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-full flex flex-col">
      <h1>Layout</h1>
      <Private />
      {children}
    </div>
  );
}
